---
version: 1
kind: generic
spec:
  name: No Dependabot PR/MR older than 30d
  serviceSelector: ".alias"
  successCondition: ".open | all(.age < 30)"
  message: |
    {% if check.passed %}
      ### Check passed
    {% else %}
      ### Check failed
      Service **{{ data.alias }}** has dependabot MRs older than 30 days.

      <table>
        <tbody>
          {%- for mr in data.open -%}
          {%- if mr.age > 30 -%}
          <tr>
            <td><a target="_blank" href="{{ mr.url }}">{{ mr.title }}</a></td>
            <td>{{ mr.age}} days</td>
          </tr>
          {%- endif -%}
          {%- endfor -%}
        </tbody>
      </table>
    </br>
    {%- endif %}
  samplePayload: '{"open":[{"age":2,"url":"https://gitlab.com/COMPANY_NAME/REPOSITORY_NAME/-/merge_requests/54","title":"Bump
    mysql-connector-python from 8.0.30 to 8.0.31"},{"age":6,"url":"https://gitlab.com/COMPANY_NAME/REPOSITORY_NAME/-/merge_requests/54","title":"Bump
    sqlalchemy from 1.4.40 to 1.4.44"},{"age":15,"url":"https://gitlab.com/COMPANY_NAME/REPOSITORY_NAME/-/merge_requests/54","title":"Bump
    requests from 2.27.1 to 2.28.1"}],"alias":"COMPANY_NAME/REPOSITORY_NAME"}'
  sampleQueryParams: alias[]=service1&alias[]=service2
  notes: 'This is a custom event check to validate if there are any PR/MR's older than 30 days.'